name = "Hugo Science"
license = "MIT"
licenselink = "https://github.com/way2ml/hugo-science/blob/master/LICENSE"
description = "A science hugo theme"

homepage = "https://github.com/way2ml/hugo-science"

demosite = "https://way2ml.github.io/"

tags = ["blog", "science", "clean", "latex", "light", "minimal", "responsive", "simple"]
features = ["blog", "postcss", "comments", "google analytics"]

[author]
    name = "Jie Huang"
    homepage = "https://way2ml.github.io/"

[original]
    author = "Michael Neuper"
    repo = "https://github.com/michaelneuper/hugo-texify3"
    
