baseURL = "https://way2ml.github.io"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
paginate = 5
rssLimit = 10
theme = "hugo-science"
title = "Info. Physics"

[author]
name = "Jie Huang"
email = "jie.huang@aalto.fi"

[taxonomies]
tags = "tags"
categories = "categories"

[params]
title="Information and Physics"
description = "Understand Physcis through Machine Learning"
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = false
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = false

[params.commentEngine]
code = """
<script src="https://giscus.app/client.js"
      data-repo="way2ml/comments"
      data-repo-id="R_kgDOGRwKvQ"
      data-category="General"
      data-category-id="DIC_kwDOGRwKvc4ChuA7"
      data-mapping="pathname"
      data-strict="0"
      data-reactions-enabled="0"
      data-emit-metadata="0"
      data-input-position="top"
      data-theme="light"
      data-lang="en"
      data-loading="lazy"
      crossorigin="anonymous"
      async>
</script>
"""

[params.buymeacoffee]
code = """
  <script data-name="BMC-Widget"
        data-cfasync="false"
        src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js"
        data-id="jiehuangfiv"
        data-description="Support us on Buy me a coffee!"
        data-message=""
        data-color="#34928C"
        data-position="Right"
        data-x_margin="18"
        data-y_margin="18"
        crossorigin="anonymous">
        </script>
"""


